In [ ]:
import tensorflow as tf


tensor_zeros = tf.zeros([2, 3])

print(tensor_zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
import tensorflow as tf
X = [[1,2,3],
     [4,5,6]]
tensor_zeros_like = tf.zeros_like(X)

print("Tensor X ban dau: \n", X)
print("\nTensor toan so 0 co cung kich thuoc va dtype voi X:\n", tensor_zeros_like)

Tensor X ban dau: 
 [[1, 2, 3], [4, 5, 6]]

Tensor toan so 0 co cung kich thuoc va dtype voi X:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf


t_3 = tf.fill([3,2],5)

print(t_3)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [ ]:
import tensorflow as tf

tensor_linspace = tf.linspace(5.0, 10.0, 50)
print(tensor_linspace)


tf.Tensor(
[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ], shape=(50,), dtype=float32)


In [ ]:
import tensorflow as tf
range_tensor = tf.range(10.0,100.0, delta = 2.0)
print(range_tensor)


tf.Tensor(
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50. 52. 54. 56. 58. 60. 62. 64. 66. 68. 70. 72. 74. 76. 78. 80.
 82. 84. 86. 88. 90. 92. 94. 96. 98.], shape=(45,), dtype=float32)


In [ ]:
import tensorflow as tf
tensor_normal = tf.random.normal(shape=[3,2], mean = 0.0, stddev = 2.0)
print(tensor_normal)

tf.Tensor(
[[ 1.107893  -2.7636712]
 [-1.2350005 -1.8550241]
 [-1.1251324 -1.6350076]], shape=(3, 2), dtype=float32)


In [ ]:
import tensorflow as tf
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
shuffled_X = tf.random.shuffle(X)
print(shuffled_X)

tf.Tensor(
[[1 2]
 [5 6]
 [3 4]], shape=(3, 2), dtype=int32)


In [ ]:

tensor_9 = tf.random.normal(shape=[10, 10, 3])


cropped_tensor = tf.image.random_crop(tensor_9, size=[5, 5, 3])

print("Bài 9 - Kích thước tensor ban đầu:", tensor_9.shape)
print("Bài 9 - Kích thước tensor sau khi crop:", cropped_tensor.shape)

Bài 9 - Kích thước tensor ban đầu: (10, 10, 3)
Bài 9 - Kích thước tensor sau khi crop: (5, 5, 3)


In [ ]:

x = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)
y = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)

print("Bài 10 - Tensor x:", x.numpy())
print("Bài 10 - Tensor y:", y.numpy())


result_10 = tf.where(x < y, x + y, x - y)

print("Kết quả:", result_10.numpy())

Bài 10 - Tensor x: [2 0 5 6 6]
Bài 10 - Tensor y: [8 7 1 8 5]
Kết quả: [10  7  4 14  1]


In [ ]:
import tensorflow as tf
x = tf.random.uniform([3, 2], minval=5, maxval=10)

y = tf.random.uniform([2, 3], minval=15, maxval=20)

print("Bài 11 - Tensor x:\n", x)
print("Bài 11 - Tensor y:\n", y)
diag_x = tf.linalg.diag_part(x)
print("\nĐường chéo của x:", diag_x)


y_transposed = tf.transpose(y)


result_11 = x + y_transposed
print("\nKết quả x + transpose(y):\n", result_11)


Bài 11 - Tensor x:
 tf.Tensor(
[[9.29854   9.311792 ]
 [9.973684  9.597692 ]
 [8.755867  6.3001165]], shape=(3, 2), dtype=float32)
Bài 11 - Tensor y:
 tf.Tensor(
[[19.876984 16.008661 15.18748 ]
 [19.945473 17.367672 16.009125]], shape=(2, 3), dtype=float32)

Đường chéo của x: tf.Tensor([9.29854  9.597692], shape=(2,), dtype=float32)

Kết quả x + transpose(y):
 tf.Tensor(
[[29.175524 29.257265]
 [25.982346 26.965363]
 [23.943348 22.309242]], shape=(3, 2), dtype=float32)


In [ ]:
#Bài 12
import tensorflow as tf

# 1. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước (3, 2, 2)
def create_tensors():
    # Sử dụng phân phối chuẩn (normal) hoặc đều (uniform) đều được
    x = tf.random.normal(shape=(3, 2, 2))
    y = tf.random.normal(shape=(3, 2, 2))
    return x, y

# 2. Viết các hàm tính cộng, trừ, nhân, chia (Python thuần túy)
def add_func(x, y):
    return tf.add(x, y)

def sub_func(x, y):
    return tf.subtract(x, y)

def mul_func(x, y):
    return tf.multiply(x, y)

def div_func(x, y):
    return tf.divide(x, y)

# 3. Chuyển các hàm này vào trong Graph

graph_add = tf.function(add_func)
graph_sub = tf.function(sub_func)
graph_mul = tf.function(mul_func)
graph_div = tf.function(div_func)


# Gọi hàm tạo tensor
x_val, y_val = create_tensors()

# Gọi các hàm đã được chuyển sang Graph
res_add = graph_add(x_val, y_val)
res_sub = graph_sub(x_val, y_val)
res_mul = graph_mul(x_val, y_val)
res_div = graph_div(x_val, y_val)

print("Kích thước tensor x:", x_val.shape)
print("Kích thước kết quả phép CỘNG trên Graph:", res_add.shape)
print("Kích thước kết quả phép TRỪ trên Graph:", res_sub.shape)
print("Kích thước kết quả phép NHÂN trên Graph:", res_mul.shape)
print("Kích thước kết quả phép CHIA trên Graph:", res_div.shape)

Kích thước tensor x: (3, 2, 2)
Kích thước kết quả phép CỘNG trên Graph: (3, 2, 2)
Kích thước kết quả phép TRỪ trên Graph: (3, 2, 2)
Kích thước kết quả phép NHÂN trên Graph: (3, 2, 2)
Kích thước kết quả phép CHIA trên Graph: (3, 2, 2)


In [ ]:
# Bài 13: Model tính tổng
class SumModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return tf.add(x, y)

# Bài 14: Model tính hiệu và tích
class SubMulModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return tf.subtract(x, y), tf.multiply(x, y)

# Chạy thử
x_val, y_val = tf.constant(10.0), tf.constant(5.0)
print("x: ", x_val.numpy(), "| y: ", y_val.numpy())
model_13 = SumModel()
print("Bài 13 - Tổng:", model_13(x_val, y_val).numpy())

model_14 = SubMulModel()
sub_res, mul_res = model_14(x_val, y_val)
print("Bài 14 - Hiệu:", sub_res.numpy(), "| Tích:", mul_res.numpy())

x:  10.0 | y:  5.0
Bài 13 - Tổng: 15.0
Bài 14 - Hiệu: 5.0 | Tích: 50.0


In [ ]:
# Bài 15: Tính chu vi hình chữ nhật
class RectanglePerimeter(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return (a + b) * 2.0

# Bài 16: Tính diện tích toàn phần hình hộp chữ nhật
class BoxSurfaceArea(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        # S_xung_quanh = (a + b) * c * 2
        s_xq = (a + b) * c * 2.0
        # S_toan_phan = (a * b) * 2 + S_xung_quanh
        s_tp = (a * b) * 2.0 + s_xq
        return s_tp

model_15 = RectanglePerimeter()
print("Bài 15 - Chu vi HCN (a=3, b=4):", model_15(3.0, 4.0).numpy())

model_16 = BoxSurfaceArea()
print("Bài 16 - Diện tích TP hộp (a=2, b=3, c=4):", model_16(2.0, 3.0, 4.0).numpy())

Bài 15 - Chu vi HCN (a=3, b=4): 14.0
Bài 16 - Diện tích TP hộp (a=2, b=3, c=4): 52.0


In [ ]:
# Bài 17: Điều kiện cạnh bên song song
class ParallelSidesModel(tf.Module):
    @tf.function
    def __call__(self, AD, BC, AB, CD):
        cond1 = tf.equal(AD, BC)
        cond2 = tf.equal(AB, CD)
        return tf.logical_and(cond1, cond2)

# Bài 18: Điều kiện cạnh đáy bằng nhau
class EqualBasesModel(tf.Module):
    @tf.function
    def __call__(self, AD, BC, is_AD_parallel_BC):
        # is_AD_parallel_BC là boolean tensor biểu diễn tính song song
        cond1 = tf.equal(AD, BC)
        return tf.logical_and(cond1, is_AD_parallel_BC)

# Bài 19: Đường trung bình tam giác
class TriangleMidlineModel(tf.Module):
    @tf.function
    def __call__(self, AM, MB, AN, NC):
        # Hệ quả của đường trung bình: Nếu AM = MB và AN = NC thì M, N là trung điểm
        # Code này sẽ trả về True nếu thực sự M và N là trung điểm các cạnh
        is_M_midpoint = tf.equal(AM, MB)
        is_N_midpoint = tf.equal(AN, NC)
        return tf.logical_and(is_M_midpoint, is_N_midpoint)

model_17 = ParallelSidesModel()
print("Bài 17 - Cạnh bên song song?:", model_17(5.0, 5.0, 4.0, 4.0).numpy())

model_18 = EqualBasesModel()
print("Bài 18 - Cạnh đáy bằng nhau?:", model_18(5.0, 5.0, tf.constant(True)).numpy())

model_19 = TriangleMidlineModel()
print("Bài 19 - NA == NC (N là trung điểm)?:", model_19(3.0, 3.0, 4.0, 4.0).numpy())

Bài 17 - Cạnh bên song song?: True
Bài 18 - Cạnh đáy bằng nhau?: True
Bài 19 - NA == NC (N là trung điểm)?: True
