In [ ]:
import numpy as np


arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng 3x3 ngẫu nhiên vừa tạo:\n", arr)


check_all_nonzero = np.all(arr != 0)

print("\nTất cả các phần tử trong mảng đều khác 0:", check_all_nonzero)

Mảng 3x3 ngẫu nhiên vừa tạo:
 [[19  9 11]
 [ 5  7  7]
 [ 9  9 15]]

Tất cả các phần tử trong mảng đều khác 0: True


In [ ]:
arr = np.random.randint(0,21, size=(3,3))
print("Mảng 3x3 ngẫu nhiên vừa tạo:\n", arr)

check_any_nonzero = np.any(arr != 0)
print("\nTồn tại ít nhất một phần tử khác 0 trong toàn bộ mảng:", check_any_nonzero)

Mảng 3x3 ngẫu nhiên vừa tạo:
 [[ 5 11  1]
 [ 7 14  3]
 [ 5 11 13]]

Tồn tại ít nhất một phần tử khác 0 trong toàn bộ mảng: True


In [ ]:
import numpy as np

print("so sanh mang 1 chieu")
a1 = np.array([10,20,30,40])
b1 = np.array([15,20,25,50])
print("mang a1: ",a1)
print("Mang b1: ",b1)
# lon hon
print("\na1 > b1 (greater):")
print(np.greater(a1,b1))

print("\na1 >= b1 (greater_equal):")
print(np.greater_equal(a1,b1))
#nho hon
print("\na1 < b1 (greater):")
print(np.less(a1,b1))

print("\na1 <= b1 (greater_equal):")
print(np.less_equal(a1,b1))

#so sanh mang 2 chieu

print("\nSo sanh mang 2 chieu")
a2 = np.array([[1,5,9],
               [8,2,6]])
b2 = np.array([[3,5,7],
               [4,9,6]])

print("Mang a2: \n",a2)
print("Mang b2: \n",b2)

print("\na2 > b2 (greater):")
print(np.greater(a2,b2))

print("\na2 >= b2 (greater_equal):")
print(np.greater_equal(a2,b2))
#nho hon
print("\na1 < b1 (greater):")
print(np.less(a1,b1))

print("\na1 <= b1 (greater_equal):")
print(np.less_equal(a1,b1))

so sanh mang 1 chieu
mang a1:  [10 20 30 40]
Mang b1:  [15 20 25 50]

a1 > b1 (greater):
[False False  True False]

a1 >= b1 (greater_equal):
[False  True  True False]

a1 < b1 (greater):
[ True False False  True]

a1 <= b1 (greater_equal):
[ True  True False  True]

So sanh mang 2 chieu
Mang a2: 
 [[1 5 9]
 [8 2 6]]
Mang b2: 
 [[3 5 7]
 [4 9 6]]

a2 > b2 (greater):
[[False False  True]
 [ True False False]]

a2 >= b2 (greater_equal):
[[False  True  True]
 [ True False  True]]

a1 < b1 (greater):
[ True False False  True]

a1 <= b1 (greater_equal):
[ True  True False  True]


In [ ]:
import numpy as np

# Tạo mảng gồm 10 số 1
array_ones = np.ones(10)

# Tạo mảng gồm 10 số 0
array_zeros = np.zeros(10)

# Tạo mảng gồm 10 số 5 (sử dụng hàm np.full để điền toàn bộ bằng số 5)
array_fives = np.full(10, 5)

# Nối 3 mảng lại với nhau thành một mảng 1 chiều duy nhất
result_array = np.concatenate((array_ones, array_zeros, array_fives))

print("Mảng kết quả:\n", result_array)
print("\nKích thước của mảng:", result_array.shape)

Mảng kết quả:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

Kích thước của mảng: (30,)


In [ ]:
import numpy as np

even_array = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:\n", even_array)
print("\nSố lượng phần tử trong mảng:", even_array.size)

Mảng các số nguyên chẵn từ 30 đến 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

Số lượng phần tử trong mảng: 21


In [ ]:
import numpy as np


identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:\n", identity_matrix)

Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
import pandas as pd

arr_7 = np.random.randint(15, 56, size=10)
print("Mảng ban đầu:\n", arr_7)


print("\nMảng sau khi bỏ phần tử đầu và cuối:\n", arr_7[1:-1])

Mảng ban đầu:
 [17 27 30 36 34 26 52 31 21 17]

Mảng sau khi bỏ phần tử đầu và cuối:
 [27 30 36 34 26 52 31 21]


In [ ]:

arr_8 = np.random.randint(0, 21, size=20)
print("Mảng ban đầu:\n", arr_8)


mask = (arr_8 >= 9) & (arr_8 <= 15)

# Đổi dấu các phần tử tại các vị trí đó
arr_8[mask] *= -1

print("\nMảng sau khi đổi dấu:\n", arr_8)

Mảng ban đầu:
 [ 0 14 11 15 16  0  8 19  6 10 10  1  8  9 10  6 13 13 20 19]

Mảng sau khi đổi dấu:
 [  0 -14 -11 -15  16   0   8  19   6 -10 -10   1   8  -9 -10   6 -13 -13
  20  19]


In [ ]:

arr_9 = np.ones.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:\n", arr_9)

Ma trận 3x4:
 [[14 13 17 21]
 [15 14 21 16]
 [17 21 13 12]]


In [ ]:
arr_10 = np.ones((10,10), dtype= int)
arr_10[1:-1,1:-1] = 0
print("Ma tran 10 x 10 bien 1, loi 0\n", arr_10)

Ma tran 10 x 10 bien 1, loi 0
 [[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
arr_11 = np.diag([1, 2, 3, 4, 5])
print("Ma trận đường chéo:\n", arr_11)

Ma trận đường chéo:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
arr_12 = np.random.randint(1, 10, size=(3, 3, 3))
print("Mảng 3x3x3:\n", arr_12)

sum_rows = arr_12.sum(axis=2)
print("\nTổng theo mỗi dòng:\n", sum_rows)

sum_cols = arr_12.sum(axis=1)
print("\nTổng theo mỗi cột:\n", sum_cols)

Mảng 3x3x3:
 [[[5 6 3]
  [1 9 2]
  [8 6 9]]

 [[4 8 6]
  [7 2 4]
  [8 3 2]]

 [[1 5 1]
  [1 4 7]
  [5 2 8]]]

Tổng theo mỗi dòng:
 [[14 12 23]
 [18 13 13]
 [ 7 12 15]]

Tổng theo mỗi cột:
 [[14 21 14]
 [19 13 12]
 [ 7 11 16]]


In [ ]:

v1 = np.random.randint(1, 10, size=10)
v2 = np.random.randint(1, 10, size=10)

print("Vector 1:", v1)
print("Vector 2:", v2)

inner_product = np.dot(v1, v2)
print("\nTích vô hướng (Inner product):", inner_product)

Vector 1: [6 1 8 7 6 4 8 7 2 4]
Vector 2: [2 7 4 5 6 3 3 5 3 2]

Tích vô hướng (Inner product): 207


In [ ]:
A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)

print("Ma trận A:\n", A)
print("\nVector y:\n", y)

result_14 = A + y
print("\nKết quả A + y:\n", result_14)

Ma trận A:
 [[4 5 8]
 [7 8 8]
 [1 6 9]
 [8 8 2]]

Vector y:
 [7 5 2]

Kết quả A + y:
 [[11 10 10]
 [14 13 10]
 [ 8 11 11]
 [15 13  4]]


In [2]:
import numpy as np
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", s1.values)
print("Series 2:\n", s2.values)

print("\n--- KẾT QUẢ ---")
print("Cộng:\n", (s1 + s2).values)
print("Trừ:\n", (s1 - s2).values)
print("Nhân:\n", (s1 * s2).values)
print("Chia:\n", (s1 / s2).values)

Series 1:
 [ 2  4  6  8 10]
Series 2:
 [ 1  3  5  7 10]

--- KẾT QUẢ ---
Cộng:
 [ 3  7 11 15 20]
Trừ:
 [1 1 1 1 0]
Nhân:
 [  2  12  30  56 100]
Chia:
 [2.         1.33333333 1.2        1.14285714 1.        ]


In [3]:
import pandas as pd
import numpy as np


df_16 = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})


series_16 = df_16.iloc[:, 0]
print("Cột đầu tiên dưới dạng Series:\n", series_16)

Cột đầu tiên dưới dạng Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [4]:
df_17 = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), columns=['A', 'B', 'C'])
print("DataFrame ban đầu:\n", df_17)


df_17_sorted = df_17.sort_values(by='A')
print("\nDataFrame sau khi sắp xếp theo cột A:\n", df_17_sorted)

DataFrame ban đầu:
     A   B   C
0  53  19  77
1  72  84  26
2  91  47  61
3  25   2  49

DataFrame sau khi sắp xếp theo cột A:
     A   B   C
3  25   2  49
0  53  19  77
1  72  84  26
2  91  47  61


In [5]:
sr_18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Series ban đầu:\n", sr_18)


sr_18_reindexed = sr_18.reindex(['B', 'A', 'C', 'D', 'E'])
print("\nSeries sau khi đổi index:\n", sr_18_reindexed)

Series ban đầu:
 A    1
B    2
C    3
D    4
E    5
dtype: int64

Series sau khi đổi index:
 B    2
A    1
C    3
D    4
E    5
dtype: int64


In [6]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])


result_19 = sr1[~sr1.isin(sr2)]
print("Các phần tử có trong sr1 nhưng không có trong sr2:\n", result_19)

Các phần tử có trong sr1 nhưng không có trong sr2:
 0    1
2    3
4    5
dtype: int64


In [7]:
x_20 = pd.Series(np.random.randint(1, 50, 20))
y_20 = pd.Series(np.random.randint(1, 50, 20))

# Hội (Union) - Lấy tất cả các phần tử duy nhất của cả 2 mảng
union_result = np.union1d(x_20, y_20)

# Giao (Intersect) - Lấy các phần tử xuất hiện ở cả 2 mảng
intersect_result = np.intersect1d(x_20, y_20)

print("Tập hợp Hội (Union):\n", union_result)
print("\nTập hợp Giao (Intersect):\n", intersect_result)

Tập hợp Hội (Union):
 [ 2  3  4  5  7  8 11 13 14 20 23 24 28 29 31 32 33 34 37 40 41 42 43 45
 47 48 49]

Tập hợp Giao (Intersect):
 [13 31 34 49]


In [8]:
x_21 = pd.Series([0, 1, 2, 7, 8, 9])
y_21 = pd.Series(['p', 'q', 'r', 'w', 'x', 'y'])

# Nối chiều dọc (vertical) - tạo thành Series dài hơn
vertical_concat = pd.concat([x_21, y_21], axis=0, ignore_index=True)
print("Nối dọc (Series):\n", vertical_concat)

# Nối chiều ngang (horizontal) - tạo thành DataFrame
horizontal_concat = pd.concat([x_21, y_21], axis=1)
print("\nNối ngang (DataFrame):\n", horizontal_concat)

Nối dọc (Series):
 0     0
1     1
2     2
3     7
4     8
5     9
6     p
7     q
8     r
9     w
10    x
11    y
dtype: object

Nối ngang (DataFrame):
    0  1
0  0  p
1  1  q
2  2  r
3  7  w
4  8  x
5  9  y


In [9]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_exam = pd.DataFrame(exam_data, index=labels)
print("--- Bài 22: DataFrame ban đầu ---\n", df_exam)

# Bài 23: Cho biết 3 dòng đầu tiên
print("\n--- Bài 23: 3 dòng đầu tiên ---")
print(df_exam.head(3))

# Bài 24: Chọn cột 'name' và 'score'
print("\n--- Bài 24: Cột 'name' và 'score' ---")
print(df_exam[['name', 'score']])

# Bài 25: Chọn những dòng có attempts > 2
print("\n--- Bài 25: attempts > 2 ---")
print(df_exam[df_exam['attempts'] > 2])

# Bài 26: Cho biết số dòng, số cột của DataFrame
rows, cols = df_exam.shape
print(f"\n--- Bài 26: Số dòng, số cột ---\nSố dòng: {rows}, Số cột: {cols}")

# Bài 27: Những dòng có score là NaN
print("\n--- Bài 27: score là NaN ---")
print(df_exam[df_exam['score'].isnull()])

# Bài 28: Những dòng có score trong khoảng (15, 20) (tính cả 15 và 20)
print("\n--- Bài 28: score trong khoảng [15, 20] ---")
print(df_exam[df_exam['score'].between(15, 20)])

# Bài 29: Những dòng có attempt > 2 VÀ score trong khoảng (15, 20)
print("\n--- Bài 29: attempts > 2 VÀ score trong khoảng [15, 20] ---")
# Lưu ý đặt điều kiện trong dấu ngoặc tròn () khi dùng toán tử &
print(df_exam[(df_exam['attempts'] > 2) & (df_exam['score'].between(15, 20))])

# Bài 30: Thay đổi giá trị dòng 'd', cột score là 19 (sử dụng .loc)
print("\n--- Bài 30: Thay đổi score dòng 'd' thành 19 ---")
df_exam.loc['d', 'score'] = 19
print(df_exam)

--- Bài 22: DataFrame ban đầu ---
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

--- Bài 23: 3 dòng đầu tiên ---
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

--- Bài 24: Cột 'name' và 'score' ---
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

--- Bài 25: attempts > 2 ---
      name  score  attempts qualify
b     Dima    9.0         3      no
d